// lib/data.ts — Datos hardcoded: 13 ciclos y 52 fases lunares en español

export type MoonPhase = '🌑' | '🌒' | '🌓' | '🌔' | '🌕' | '🌖' | '🌗' | '🌘';

export interface Phase {
  id: string;
  cycleId: number;
  phaseIndex: number;
  moon: MoonPhase;
  name: string;
  date: string; // ISO YYYY-MM-DD
  sign: string;
  theme: string;
  suggestions: string[];
  isSolarEvent?: string; // nombre del evento solar si aplica
}

export interface Cycle {
  id: number;
  sign: string;
  glyph: string;
  period: string;
  startDate: string;
  endDate: string;
  centralTheme: string;
  description: string;
  phases: Phase[];
  isFree: boolean; // El ciclo 0 es gratuito
}

export const CYCLES: Cycle[] = [
  {
    id: 0,
    sign: 'Piscis · Punto Cero',
    glyph: '♓',
    period: '18 mar → 17 abr 2026',
    startDate: '2026-03-18',
    endDate: '2026-04-17',
    centralTheme: 'Disolución · cierre · preparación',
    description: 'El año astrológico aún no ha comenzado. Estamos en el umbral. Es tiempo de soltar lo que ya no sirve, cerrar ciclos y preparar el terreno interior para lo que viene.',
    isFree: true,
    phases: [
      {
        id: 'piscis-26-1',
        cycleId: 0,
        phaseIndex: 1,
        moon: '🌑',
        name: 'Luna Nueva',
        date: '2026-03-18',
        sign: 'Piscis ♓',
        theme: 'El punto cero y el umbral de la primavera (Equinoccio el 20 mar). ¿Qué estás dejando atrás para abrirte al nuevo ciclo?',
        suggestions: [
          'Escribe todo lo que quieres soltar este año',
          'Haz una limpieza simbólica de tu espacio de trabajo',
          'Revisa tus proyectos pendientes y decide cuáles cierras',
          'Crea un ritual de inicio de primavera el día 20',
        ],
        isSolarEvent: 'Equinoccio de Primavera (20 mar)',
      },
      {
        id: 'piscis-26-2',
        cycleId: 0,
        phaseIndex: 2,
        moon: '🌓',
        name: 'Cuarto Creciente',
        date: '2026-03-25',
        sign: 'Cáncer ♋',
        theme: 'Primer movimiento. ¿Qué acción concreta de cierre o limpieza emprendes?',
        suggestions: [
          'Toma acción sobre algo que has estado posponiendo',
          'Define una sola prioridad para esta semana',
          'Comunica un límite o cierre a alguien que lo necesita',
          'Ordena tu espacio digital: carpetas, correos, archivos',
        ],
      },
      {
        id: 'piscis-26-3',
        cycleId: 0,
        phaseIndex: 3,
        moon: '🌕',
        name: 'Luna Llena',
        date: '2026-04-02',
        sign: 'Libra ♎',
        theme: 'Iluminación en las relaciones. ¿Qué alianzas potencias y cuáles liberas?',
        suggestions: [
          'Celebra los vínculos que nutren tu trabajo',
          'Define con quién quieres colaborar este año',
          'Revisa contratos o acuerdos que necesitan ajuste',
          'Comparte tu visión con alguien de confianza',
        ],
      },
      {
        id: 'piscis-26-4',
        cycleId: 0,
        phaseIndex: 4,
        moon: '🌗',
        name: 'Cuarto Menguante',
        date: '2026-04-09',
        sign: 'Capricornio ♑',
        theme: 'Revisión profunda. ¿Qué estructuras del año pasado ya no funcionan?',
        suggestions: [
          'Audita tus sistemas y procesos de trabajo',
          'Identifica los hábitos que sabotean tu productividad',
          'Simplifica: elimina una herramienta o compromiso innecesario',
          'Medita sobre qué tipo de disciplina quieres cultivar',
        ],
      },
    ],
  },
  {
    id: 1,
    sign: 'Aries',
    glyph: '♈',
    period: '17 abr → 15 may 2026',
    startDate: '2026-04-17',
    endDate: '2026-05-15',
    centralTheme: 'Año nuevo astrológico · intención · valentía',
    description: 'Aries inaugura el año con fuego. Es el momento del inicio audaz, de la chispa creadora, de las decisiones que marcan rumbo. Actúa antes de que el miedo encuentre argumentos.',
    isFree: false,
    phases: [
      {
        id: 'aries-26-1',
        cycleId: 1,
        phaseIndex: 1,
        moon: '🌑',
        name: 'Luna Nueva',
        date: '2026-04-17',
        sign: 'Aries ♈',
        theme: 'Año nuevo. ¿Qué proyecto audaz lanzas ahora?',
        suggestions: [
          'Escribe las 3 intenciones principales del año astrológico',
          'Lanza un nuevo proyecto o producto',
          'Define tus metas anuales con fechas límite',
          'Crea un ritual de inicio de ciclo',
        ],
      },
      {
        id: 'aries-26-2',
        cycleId: 1,
        phaseIndex: 2,
        moon: '🌓',
        name: 'Cuarto Creciente',
        date: '2026-04-24',
        sign: 'Cáncer ♋',
        theme: 'Primer obstáculo. ¿Qué ajustas sin abandonar la dirección?',
        suggestions: [
          'Identifica el principal freno a tu proyecto principal',
          'Comunica tu visión a tu equipo o comunidad',
          'Busca un mentor o colega que ya recorrió este camino',
          'Ajusta el plan sin perder el norte',
        ],
      },
      {
        id: 'aries-26-3',
        cycleId: 1,
        phaseIndex: 3,
        moon: '🌕',
        name: 'Luna Llena',
        date: '2026-05-01',
        sign: 'Escorpio ♏',
        theme: 'Cosecha de valentía. ¿Qué has iniciado que merece celebración?',
        suggestions: [
          'Celebra los primeros pasos dados en el ciclo',
          'Haz una revisión honesta: ¿qué funciona y qué no?',
          'Amplifica lo que ya está dando resultados',
          'Suelta el perfeccionismo y publica algo',
        ],
      },
      {
        id: 'aries-26-4',
        cycleId: 1,
        phaseIndex: 4,
        moon: '🌗',
        name: 'Cuarto Menguante',
        date: '2026-05-08',
        sign: 'Acuario ♒',
        theme: 'Integración. ¿Cómo sostienes el ritmo iniciado?',
        suggestions: [
          'Crea rutinas de trabajo que sostengan tu impulso',
          'Documenta los aprendizajes del primer mes del año',
          'Identifica a quién puedes delegar',
          'Prepara la energía para el siguiente ciclo: Tauro',
        ],
      },
    ],
  },
  {
    id: 2,
    sign: 'Tauro',
    glyph: '♉',
    period: '16 may → 13 jun 2026',
    startDate: '2026-05-16',
    endDate: '2026-06-13',
    centralTheme: 'Arraigo · manifestación · recursos',
    description: 'Tauro ancla las intenciones de Aries en la tierra. Es tiempo de construir, de crear valor tangible, de cuidar los recursos y de confiar en el ritmo lento de lo que crece bien.',
    isFree: false,
    phases: [
      {
        id: 'tauro-26-1',
        cycleId: 2,
        phaseIndex: 1,
        moon: '🌑',
        name: 'Luna Nueva',
        date: '2026-05-16',
        sign: 'Tauro ♉',
        theme: '¿Qué construyes ahora que tiene valor real y duradero?',
        suggestions: [
          'Define tu propuesta de valor más concreta',
          'Revisa y ordena tus finanzas del mes',
          'Crea o mejora un proceso que genere ingresos recurrentes',
          'Planta algo: un proyecto, un hábito, una relación de negocio',
        ],
      },
      {
        id: 'tauro-26-2',
        cycleId: 2,
        phaseIndex: 2,
        moon: '🌓',
        name: 'Cuarto Creciente',
        date: '2026-05-23',
        sign: 'Leo ♌',
        theme: 'Creatividad con recursos. ¿Cómo expresas tu valor de forma magnética?',
        suggestions: [
          'Actualiza tu presencia visual o bio profesional',
          'Crea un contenido que muestre tu proceso de trabajo',
          'Invierte en algo que mejore tu herramienta principal',
          'Conéctate con otros creativos de tu sector',
        ],
      },
      {
        id: 'tauro-26-3',
        cycleId: 2,
        phaseIndex: 3,
        moon: '🌕',
        name: 'Luna Llena',
        date: '2026-05-31',
        sign: 'Sagitario ♐',
        theme: 'Expansión del valor. ¿Qué posibilidades más grandes aparecen?',
        suggestions: [
          'Explora un mercado o audiencia que aún no has trabajado',
          'Sube el precio de un servicio o producto',
          'Comparte tu trabajo en un espacio nuevo (podcast, evento, artículo)',
          'Define tu visión financiera a largo plazo',
        ],
      },
      {
        id: 'tauro-26-4',
        cycleId: 2,
        phaseIndex: 4,
        moon: '🌗',
        name: 'Cuarto Menguante',
        date: '2026-06-07',
        sign: 'Piscis ♓',
        theme: 'Gratitud e integración. ¿Qué abundancia, por pequeña que sea, reconoces hoy?',
        suggestions: [
          'Escribe 5 cosas que el ciclo Tauro te ha dado',
          'Simplifica: elimina lo que ocupa espacio sin generar valor',
          'Programa tiempo de descanso en las próximas semanas',
          'Prepara la energía más comunicativa de Géminis',
        ],
      },
    ],
  },
  {
    id: 3,
    sign: 'Géminis',
    glyph: '♊',
    period: '14 jun → 12 jul 2026',
    startDate: '2026-06-14',
    endDate: '2026-07-12',
    centralTheme: 'Comunicación · conexión · Solsticio de Verano',
    description: 'Géminis trae curiosidad, velocidad mental y el poder de las palabras. Es el ciclo ideal para comunicar, crear contenido, establecer conexiones y aprender lo que necesitas para crecer.',
    isFree: false,
    phases: [
      {
        id: 'geminis-26-1',
        cycleId: 3,
        phaseIndex: 1,
        moon: '🌑',
        name: 'Luna Nueva',
        date: '2026-06-14',
        sign: 'Géminis ♊',
        theme: '¿Qué mensaje quieres que el mundo reciba de ti este ciclo?',
        suggestions: [
          'Define los temas sobre los que hablarás durante el ciclo',
          'Prepara un lanzamiento de contenido o newsletter',
          'Contacta a 3 personas con quienes no has hablado en meses',
          'Lee o estudia algo fuera de tu área habitual',
        ],
        isSolarEvent: 'Solsticio de Verano',
      },
      {
        id: 'geminis-26-2',
        cycleId: 3,
        phaseIndex: 2,
        moon: '🌓',
        name: 'Cuarto Creciente',
        date: '2026-06-21',
        sign: 'Virgo ♍',
        theme: 'Organiza las ideas. ¿Cómo conversas de forma más efectiva?',
        suggestions: [
          'Crea un sistema para organizar tus ideas y notas',
          'Escribe un borrador de artículo o guía',
          'Mejora la claridad de tu comunicación con clientes',
          'Define el calendario de contenidos del mes',
        ],
      },
      {
        id: 'geminis-26-3',
        cycleId: 3,
        phaseIndex: 3,
        moon: '🌕',
        name: 'Luna Llena',
        date: '2026-06-29',
        sign: 'Capricornio ♑',
        theme: 'Cima del ciclo. ¿Qué conversación importante llegas a tener?',
        suggestions: [
          'Participa en un evento, podcast o webinar',
          'Publica tu contenido más valioso del mes',
          'Negocia o cierra un acuerdo de colaboración',
          'Recibe feedback honesto sobre tu mensaje',
        ],
      },
      {
        id: 'geminis-26-4',
        cycleId: 3,
        phaseIndex: 4,
        moon: '🌗',
        name: 'Cuarto Menguante',
        date: '2026-07-06',
        sign: 'Aries ♈',
        theme: 'Silencio estratégico. ¿Qué no necesitas decir?',
        suggestions: [
          'Descansa de redes sociales durante unos días',
          'Integra los aprendizajes del ciclo sin actuar',
          'Elimina compromisos de comunicación que drenan energía',
          'Prepara el ciclo de Cáncer: tiempo de repliegue e intuición',
        ],
      },
    ],
  },
  {
    id: 4,
    sign: 'Cáncer',
    glyph: '♋',
    period: '13 jul → 10 ago 2026',
    startDate: '2026-07-13',
    endDate: '2026-08-10',
    centralTheme: 'Cuidado · intuición · bases',
    description: 'Cáncer llama al mundo interior. Es tiempo de fortalecer las bases de tu proyecto y de tu vida: el hogar, la familia de elección, el cuidado propio como combustible para crear.',
    isFree: false,
    phases: [
      {
        id: 'cancer-26-1',
        cycleId: 4,
        phaseIndex: 1,
        moon: '🌑',
        name: 'Luna Nueva',
        date: '2026-07-13',
        sign: 'Cáncer ♋',
        theme: '¿Qué necesitas nutrir en ti para poder dar más al exterior?',
        suggestions: [
          'Establece un ritual de cuidado propio diario',
          'Reorganiza tu espacio de trabajo para que sea más acogedor',
          'Llama a alguien que te sostiene emocionalmente',
          'Identifica qué aspecto de tu negocio necesita más cuidado',
        ],
      },
      {
        id: 'cancer-26-2',
        cycleId: 4,
        phaseIndex: 2,
        moon: '🌓',
        name: 'Cuarto Creciente',
        date: '2026-07-20',
        sign: 'Libra ♎',
        theme: 'Cuidado con límites. ¿Dónde dices sí cuando quieres decir no?',
        suggestions: [
          'Practica decir no a una solicitud esta semana',
          'Revisa tus relaciones de trabajo y su equilibrio',
          'Define tus horas de trabajo y las horas libres',
          'Crea un acuerdo de colaboración más claro con alguien',
        ],
      },
      {
        id: 'cancer-26-3',
        cycleId: 4,
        phaseIndex: 3,
        moon: '🌕',
        name: 'Luna Llena',
        date: '2026-07-28',
        sign: 'Acuario ♒',
        theme: 'El corazón del ciclo. ¿Qué impacto tiene tu trabajo en la comunidad?',
        suggestions: [
          'Conecta con tu comunidad de forma genuina',
          'Comparte detrás de escena de tu proceso creativo',
          'Plantéate: ¿a quién ayuda realmente lo que hago?',
          'Invita a alguien a tu círculo de trabajo o apoyo',
        ],
      },
      {
        id: 'cancer-26-4',
        cycleId: 4,
        phaseIndex: 4,
        moon: '🌗',
        name: 'Cuarto Menguante',
        date: '2026-08-04',
        sign: 'Tauro ♉',
        theme: 'Recarga profunda. ¿Qué forma de descanso te restaura de verdad?',
        suggestions: [
          'Tómate un día sin pantallas si es posible',
          'Cocina algo con calma, camina en la naturaleza',
          'Escribe en tu diario sin propósito productivo',
          'Prepara la energía solar y creativa de Leo',
        ],
      },
    ],
  },
  {
    id: 5,
    sign: 'Leo',
    glyph: '♌',
    period: '11 ago → 8 sep 2026',
    startDate: '2026-08-11',
    endDate: '2026-09-08',
    centralTheme: 'Creatividad · liderazgo · expresión',
    description: 'Leo llega con brillo propio. Es el ciclo de mostrarte, de liderar desde el corazón, de crear con generosidad y de recordar que la autenticidad es el mayor imán.',
    isFree: false,
    phases: [
      {
        id: 'leo-26-1',
        cycleId: 5,
        phaseIndex: 1,
        moon: '🌑',
        name: 'Luna Nueva',
        date: '2026-08-11',
        sign: 'Leo ♌',
        theme: '¿Qué quieres crear o expresar que hasta ahora has guardado?',
        suggestions: [
          'Define un proyecto creativo personal para el ciclo',
          'Publica algo que te expongas más de lo habitual',
          'Comparte una opinión o perspectiva que es tuya',
          'Crea algo por el placer de crearlo, sin estrategia',
        ],
      },
      {
        id: 'leo-26-2',
        cycleId: 5,
        phaseIndex: 2,
        moon: '🌓',
        name: 'Cuarto Creciente',
        date: '2026-08-19',
        sign: 'Escorpio ♏',
        theme: 'Profundidad creativa. ¿Qué te frena de brillar completamente?',
        suggestions: [
          'Identifica el miedo que bloquea tu visibilidad',
          'Trabaja la historia que cuentas sobre ti mismo',
          'Busca feedback de alguien que admires',
          'Invierte en tu apariencia o presentación profesional',
        ],
      },
      {
        id: 'leo-26-3',
        cycleId: 5,
        phaseIndex: 3,
        moon: '🌕',
        name: 'Luna Llena',
        date: '2026-08-26',
        sign: 'Piscis ♓',
        theme: 'Expansión del corazón. ¿Qué legado creativo dejas en este ciclo?',
        suggestions: [
          'Realiza una presentación, showcase o evento de tu trabajo',
          'Regala algo de tu trabajo a alguien que lo valorará',
          'Celebra con los que te han apoyado este año',
          'Define tu aportación única al campo en que trabajas',
        ],
      },
      {
        id: 'leo-26-4',
        cycleId: 5,
        phaseIndex: 4,
        moon: '🌗',
        name: 'Cuarto Menguante',
        date: '2026-09-02',
        sign: 'Géminis ♊',
        theme: 'Integración del brillo. ¿Qué aprendiste sobre cómo te ven los demás?',
        suggestions: [
          'Recoge testimonios o reseñas de tu trabajo',
          'Documenta los proyectos del ciclo para tu portfolio',
          'Prepara la energía analítica y de mejora de Virgo',
          'Agradece a quienes te han visto brillar',
        ],
      },
    ],
  },
  {
    id: 6,
    sign: 'Virgo',
    glyph: '♍',
    period: '9 sep → 7 oct 2026',
    startDate: '2026-09-09',
    endDate: '2026-10-07',
    centralTheme: 'Análisis · perfeccionamiento · servicio',
    description: 'Virgo trae la lupa. Es tiempo de mejorar sistemas, optimizar procesos y preguntar: ¿cómo puedo ser más útil? La excelencia callada de Virgo construye sin ruido.',
    isFree: false,
    phases: [
      {
        id: 'virgo-26-1',
        cycleId: 6,
        phaseIndex: 1,
        moon: '🌑',
        name: 'Luna Nueva',
        date: '2026-09-09',
        sign: 'Virgo ♍',
        theme: '¿Qué sistema o proceso mejorarías si tuvieras el tiempo?',
        suggestions: [
          'Realiza una auditoría de tu flujo de trabajo semanal',
          'Automatiza una tarea que haces manualmente',
          'Revisa cómo estás ofreciendo tu servicio principal',
          'Establece métricas claras para lo que quieres mejorar',
        ],
      },
      {
        id: 'virgo-26-2',
        cycleId: 6,
        phaseIndex: 2,
        moon: '🌓',
        name: 'Cuarto Creciente',
        date: '2026-09-17',
        sign: 'Sagitario ♐',
        theme: 'El equilibrio entre perfección y acción. ¿Cuándo es suficientemente bueno?',
        suggestions: [
          'Define el mínimo viable para tu próximo entregable',
          'Comparte algo en proceso sin esperar que esté perfecto',
          'Conecta el detalle con la visión grande',
          'Estudia una habilidad que mejore tu servicio principal',
        ],
      },
      {
        id: 'virgo-26-3',
        cycleId: 6,
        phaseIndex: 3,
        moon: '🌕',
        name: 'Luna Llena',
        date: '2026-09-24',
        sign: 'Aries ♈',
        theme: 'Entrega. ¿Qué servicio o producto terminas y lanzas hoy?',
        suggestions: [
          'Entrega o publica el proyecto que has estado puliendo',
          'Solicita feedback estructurado a clientes actuales',
          'Documenta tu proceso de trabajo para reutilizarlo',
          'Celebra la mejora, aunque no sea perfecta',
        ],
      },
      {
        id: 'virgo-26-4',
        cycleId: 6,
        phaseIndex: 4,
        moon: '🌗',
        name: 'Cuarto Menguante',
        date: '2026-10-01',
        sign: 'Cáncer ♋',
        theme: 'Cuidado personal tras el esfuerzo. ¿Cómo te regeneras?',
        suggestions: [
          'Cuida tu cuerpo: descanso, movimiento, alimentación',
          'Organiza y archiva el material del ciclo',
          'Prepara la energía de equilibrio y decisión de Libra',
          'Escribe qué mejoró gracias a tu esfuerzo este ciclo',
        ],
      },
    ],
  },
  {
    id: 7,
    sign: 'Libra',
    glyph: '♎',
    period: '8 oct → 5 nov 2026',
    startDate: '2026-10-08',
    endDate: '2026-11-05',
    centralTheme: 'Equilibrio · alianzas · decisiones',
    description: 'Libra pondera. Es el ciclo para tomar decisiones importantes, fortalecer alianzas estratégicas y encontrar el punto de equilibrio entre dar y recibir en tus negocios.',
    isFree: false,
    phases: [
      {
        id: 'libra-26-1',
        cycleId: 7,
        phaseIndex: 1,
        moon: '🌑',
        name: 'Luna Nueva',
        date: '2026-10-08',
        sign: 'Libra ♎',
        theme: '¿Qué decisión has estado postergando que ya necesita respuesta?',
        suggestions: [
          'Lista las 3 decisiones que evitas tomar',
          'Define los criterios para tomar cada decisión',
          'Busca un socio o colaborador para el próximo proyecto',
          'Revisa tus contratos y acuerdos de colaboración',
        ],
      },
      {
        id: 'libra-26-2',
        cycleId: 7,
        phaseIndex: 2,
        moon: '🌓',
        name: 'Cuarto Creciente',
        date: '2026-10-15',
        sign: 'Capricornio ♑',
        theme: 'Decisiones con estructura. ¿Qué ruta elegida refuerzas ahora?',
        suggestions: [
          'Toma la decisión que has estado evitando',
          'Comunica tu decisión a quien corresponde',
          'Define las siguientes acciones concretas de cada elección',
          'Revisa el balance de tu negocio a mitad de año',
        ],
      },
      {
        id: 'libra-26-3',
        cycleId: 7,
        phaseIndex: 3,
        moon: '🌕',
        name: 'Luna Llena',
        date: '2026-10-23',
        sign: 'Tauro ♉',
        theme: 'Abundancia en equilibrio. ¿Tus alianzas te sostienen o te drenan?',
        suggestions: [
          'Evalúa tus relaciones de trabajo: ¿son equitativas?',
          'Negocia un nuevo acuerdo que beneficie a ambas partes',
          'Celebra las colaboraciones que han florecido',
          'Suelta una colaboración que ya no funciona',
        ],
      },
      {
        id: 'libra-26-4',
        cycleId: 7,
        phaseIndex: 4,
        moon: '🌗',
        name: 'Cuarto Menguante',
        date: '2026-10-30',
        sign: 'Leo ♌',
        theme: 'Cierre diplomático. ¿Cómo integras lo aprendido en relaciones?',
        suggestions: [
          'Agradece a quienes colaboraron contigo este ciclo',
          'Define lo que buscas en futuras alianzas',
          'Prepara la energía profunda y transformadora de Escorpio',
          'Descansa de los compromisos sociales de trabajo',
        ],
      },
    ],
  },
  {
    id: 8,
    sign: 'Escorpio',
    glyph: '♏',
    period: '6 nov → 4 dic 2026',
    startDate: '2026-11-06',
    endDate: '2026-12-04',
    centralTheme: 'Transformación · profundidad · renovación',
    description: 'Escorpio va al fondo de todo. No temas lo que encuentras. Es tiempo de transformación real, de renovar lo que ya cumplió su función y de acceder a recursos más profundos.',
    isFree: false,
    phases: [
      {
        id: 'escorpio-26-1',
        cycleId: 8,
        phaseIndex: 1,
        moon: '🌑',
        name: 'Luna Nueva',
        date: '2026-11-06',
        sign: 'Escorpio ♏',
        theme: '¿Qué parte de tu negocio o vida necesita una transformación real?',
        suggestions: [
          'Identifica un área de tu vida que resiste el cambio',
          'Haz algo que normalmente evitas por miedo',
          'Profundiza en la finanza: inversiones, deudas, herencia',
          'Investiga algo que no entiendes completamente',
        ],
      },
      {
        id: 'escorpio-26-2',
        cycleId: 8,
        phaseIndex: 2,
        moon: '🌓',
        name: 'Cuarto Creciente',
        date: '2026-11-14',
        sign: 'Acuario ♒',
        theme: 'La innovación que transforma. ¿Qué estás cambiando en tu modelo?',
        suggestions: [
          'Experimenta con un modelo de negocio diferente',
          'Prueba un formato de contenido o entrega nuevo',
          'Cuestiona un supuesto básico de tu sector',
          'Conecta con alguien que piensa diferente a ti',
        ],
      },
      {
        id: 'escorpio-26-3',
        cycleId: 8,
        phaseIndex: 3,
        moon: '🌕',
        name: 'Luna Llena',
        date: '2026-11-21',
        sign: 'Tauro ♉',
        theme: 'Profunda abundancia. ¿Qué valor real has creado este año?',
        suggestions: [
          'Calcula el impacto real de tu trabajo este año',
          'Actualiza tu portfolio o página de servicios',
          'Define el precio que mereces cobrar en 2027',
          'Celebra la transformación que has vivido',
        ],
      },
      {
        id: 'escorpio-26-4',
        cycleId: 8,
        phaseIndex: 4,
        moon: '🌗',
        name: 'Cuarto Menguante',
        date: '2026-11-28',
        sign: 'Virgo ♍',
        theme: 'Limpieza profunda. ¿Qué sueltas definitivamente para 2027?',
        suggestions: [
          'Escribe aquello que dejas ir este año',
          'Cierra proyectos, conversaciones o acuerdos pendientes',
          'Simplifica tu oferta para el próximo año',
          'Prepara la expansión de visión de Sagitario',
        ],
      },
    ],
  },
  {
    id: 9,
    sign: 'Sagitario',
    glyph: '♐',
    period: '5 dic 2026 → 2 ene 2027',
    startDate: '2026-12-05',
    endDate: '2027-01-02',
    centralTheme: 'Visión · expansión · planificación 2027',
    description: 'Sagitario mira lejos. Es el ciclo de trazar la visión del año nuevo gregoriano, de expandir horizontes y de recordar por qué empezaste. El optimismo estratégico como combustible.',
    isFree: false,
    phases: [
      {
        id: 'sagitario-26-1',
        cycleId: 9,
        phaseIndex: 1,
        moon: '🌑',
        name: 'Luna Nueva',
        date: '2026-12-05',
        sign: 'Sagitario ♐',
        theme: '¿Cuál es la visión más grande que puedes sostener para 2027?',
        suggestions: [
          'Escribe tu visión de negocio para el año nuevo',
          'Define las metas más audaces de 2027',
          'Estudia o planifica un viaje que expanda tu perspectiva',
          'Establece un propósito que vaya más allá del dinero',
        ],
      },
      {
        id: 'sagitario-26-2',
        cycleId: 9,
        phaseIndex: 2,
        moon: '🌓',
        name: 'Cuarto Creciente',
        date: '2026-12-12',
        sign: 'Piscis ♓',
        theme: 'Visión con intuición. ¿Qué te dice tu instinto sobre 2027?',
        suggestions: [
          'Medita o escribe sin estructura sobre el futuro',
          'Identifica las señales que el año te ha enviado',
          'Revisa tus intenciones de Aries: ¿cuáles se cumplieron?',
          'Define qué te da miedo del próximo año y por qué',
        ],
      },
      {
        id: 'sagitario-26-3',
        cycleId: 9,
        phaseIndex: 3,
        moon: '🌕',
        name: 'Luna Llena',
        date: '2026-12-19',
        sign: 'Géminis ♊',
        theme: 'La gran perspectiva. ¿Qué historia cuenta tu año completo?',
        suggestions: [
          'Escribe el resumen del año astrológico 2026',
          'Comparte tus logros del año con tu comunidad',
          'Lee lo que escribiste en Aries al inicio del año',
          'Celebra con quienes te acompañaron este año',
        ],
      },
      {
        id: 'sagitario-26-4',
        cycleId: 9,
        phaseIndex: 4,
        moon: '🌗',
        name: 'Cuarto Menguante',
        date: '2026-12-27',
        sign: 'Libra ♎',
        theme: 'Balance de fin de año. ¿Qué equilibras antes de cruzar al 2027?',
        suggestions: [
          'Cierra compromisos económicos del año',
          'Paga o agradece deudas simbólicas y reales',
          'Define tus palabras clave para 2027',
          'Entra al Año Nuevo Gregoriano con intención',
        ],
        isSolarEvent: 'Próximo: Año Nuevo Gregoriano 2027',
      },
    ],
  },
  {
    id: 10,
    sign: 'Capricornio',
    glyph: '♑',
    period: '3 ene → 31 ene 2027',
    startDate: '2027-01-03',
    endDate: '2027-01-31',
    centralTheme: 'Estructura · ambición · Año Nuevo gregoriano',
    description: 'Capricornio construye en el tiempo. Es el ciclo de la ambición con disciplina, de crear estructuras sólidas y de trazar el camino con paciencia para llegar alto.',
    isFree: false,
    phases: [
      {
        id: 'capricornio-27-1',
        cycleId: 10,
        phaseIndex: 1,
        moon: '🌑',
        name: 'Luna Nueva',
        date: '2027-01-03',
        sign: 'Capricornio ♑',
        theme: '¿Qué estructura profesional quieres construir este año?',
        suggestions: [
          'Define tu plan trimestral con hitos concretos',
          'Crea o actualiza tu sistema de gestión de proyectos',
          'Establece un hábito de trabajo diario no negociable',
          'Conecta con un mentor o figura de inspiración profesional',
        ],
        isSolarEvent: 'Año Nuevo Gregoriano 2027 (ene 1)',
      },
      {
        id: 'capricornio-27-2',
        cycleId: 10,
        phaseIndex: 2,
        moon: '🌓',
        name: 'Cuarto Creciente',
        date: '2027-01-10',
        sign: 'Aries ♈',
        theme: 'Acción con estructura. Primer mes del año con disciplina.',
        suggestions: [
          'Cumple el primer hito de tu plan trimestral',
          'Revisa y ajusta si algo no está funcionando',
          'Comunica tus metas de 2027 a quienes te rodean',
          'Crea un tablero visual de objetivos del año',
        ],
      },
      {
        id: 'capricornio-27-3',
        cycleId: 10,
        phaseIndex: 3,
        moon: '🌕',
        name: 'Luna Llena',
        date: '2027-01-18',
        sign: 'Cáncer ♋',
        theme: 'Ambición con corazón. ¿El éxito que buscas te nutre?',
        suggestions: [
          'Chequea si tus metas están alineadas con tus valores',
          'Define cómo cuidarás de ti mientras construyes',
          'Comparte un hito logrado con tu comunidad',
          'Reconoce el trabajo que has hecho hasta aquí',
        ],
      },
      {
        id: 'capricornio-27-4',
        cycleId: 10,
        phaseIndex: 4,
        moon: '🌗',
        name: 'Cuarto Menguante',
        date: '2027-01-25',
        sign: 'Escorpio ♏',
        theme: 'Integración y purga. ¿Qué abandonas del camino viejo?',
        suggestions: [
          'Identifica obstáculos internos a tu ambición',
          'Elimina compromisos que no sirven a tus metas 2027',
          'Prepara la energía innovadora y colectiva de Acuario',
          'Reflexiona cómo tu trabajo impacta más allá de ti',
        ],
      },
    ],
  },
  {
    id: 11,
    sign: 'Acuario',
    glyph: '♒',
    period: '1 feb → 1 mar 2027',
    startDate: '2027-02-01',
    endDate: '2027-03-01',
    centralTheme: 'Innovación · colectivo · disrupción',
    description: 'Acuario sacude el tablero. Es tiempo de pensar diferente, de conectar con comunidades afines y de apostar por lo que aún no existe pero ya puedes imaginar.',
    isFree: false,
    phases: [
      {
        id: 'acuario-27-1',
        cycleId: 11,
        phaseIndex: 1,
        moon: '🌑',
        name: 'Luna Nueva',
        date: '2027-02-01',
        sign: 'Acuario ♒',
        theme: '¿Qué idea innovadora has estado silenciando?',
        suggestions: [
          'Haz la presentación de una idea que parece demasiado grande',
          'Únete o crea un espacio colectivo de tu sector',
          'Experimenta con tecnología o herramientas que no conoces',
          'Pregunta a tu comunidad qué problema quieren que resuelvas',
        ],
      },
      {
        id: 'acuario-27-2',
        cycleId: 11,
        phaseIndex: 2,
        moon: '🌓',
        name: 'Cuarto Creciente',
        date: '2027-02-08',
        sign: 'Tauro ♉',
        theme: 'Innovación concreta. ¿Cuál de tus ideas tiene raíces reales?',
        suggestions: [
          'Prototipa la idea más prometedora del ciclo',
          'Define el modelo de negocio detrás de tu innovación',
          'Busca financiamiento o inversión si aplica',
          'Conecta con alguien que ya ejecutó algo similar',
        ],
      },
      {
        id: 'acuario-27-3',
        cycleId: 11,
        phaseIndex: 3,
        moon: '🌕',
        name: 'Luna Llena',
        date: '2027-02-16',
        sign: 'Leo ♌',
        theme: 'El brillo de lo colectivo. ¿Tu trabajo contribuye a algo mayor?',
        suggestions: [
          'Comparte tu visión de impacto con tu comunidad',
          'Lidera un proyecto colaborativo o de open source',
          'Amplifica el trabajo de otros en tu red',
          'Define tu aportación única al cambio que quieres ver',
        ],
      },
      {
        id: 'acuario-27-4',
        cycleId: 11,
        phaseIndex: 4,
        moon: '🌗',
        name: 'Cuarto Menguante',
        date: '2027-02-23',
        sign: 'Escorpio ♏',
        theme: 'Desprendimiento del ego. ¿Qué logro compartes sin necesitar crédito?',
        suggestions: [
          'Dona algo de tu trabajo: conocimiento, tiempo, recurso',
          'Prepara el cierre del año astrológico en Piscis',
          'Reflexiona sobre el impacto de tu año completo',
          'Simplifica tu vida para abrirte al próximo ciclo',
        ],
      },
    ],
  },
  {
    id: 12,
    sign: 'Piscis',
    glyph: '♓',
    period: '2 mar → 1 abr 2027',
    startDate: '2027-03-02',
    endDate: '2027-04-01',
    centralTheme: 'Cierre del año astrológico',
    description: 'El año astrológico regresa a Piscis para cerrar. Es tiempo de gratitud, de soltar lo último que quedó pendiente y de preparar el terreno para el gran inicio de Aries 2027.',
    isFree: false,
    phases: [
      {
        id: 'piscis-27-1',
        cycleId: 12,
        phaseIndex: 1,
        moon: '🌑',
        name: 'Luna Nueva',
        date: '2027-03-02',
        sign: 'Piscis ♓',
        theme: 'El último umbral. ¿Qué sueltas antes de iniciar un nuevo año?',
        suggestions: [
          'Escribe una lista de gratitud del año completo',
          'Haz una limpieza profunda de archivos y espacio',
          'Perdona (a ti o a otros) lo que quedó sin resolver',
          'Visualiza la versión más expandida de ti en el nuevo ciclo',
        ],
      },
      {
        id: 'piscis-27-2',
        cycleId: 12,
        phaseIndex: 2,
        moon: '🌓',
        name: 'Cuarto Creciente',
        date: '2027-03-10',
        sign: 'Géminis ♊',
        theme: 'Palabras de cierre. ¿Qué historia final cuentas de este año?',
        suggestions: [
          'Escribe el resumen de todo el año astrológico 2026-2027',
          'Comparte en tu comunidad los aprendizajes más importantes',
          'Documenta tus intenciones de este año para el futuro tú',
          'Define las 3 palabras que definen este año',
        ],
      },
      {
        id: 'piscis-27-3',
        cycleId: 12,
        phaseIndex: 3,
        moon: '🌕',
        name: 'Luna Llena',
        date: '2027-03-18',
        sign: 'Virgo ♍',
        theme: 'Perfección imperfecta. ¿Qué ha sido suficiente este año?',
        suggestions: [
          'Revisa cuántas intenciones del año se manifestaron',
          'Celebra los logros pequeños que no reconociste',
          'Acepta lo que no sucedió como parte del proceso',
          'Prepara el ritual de cierre del año astrológico',
        ],
        isSolarEvent: 'Próximo: Equinoccio de Primavera 2027',
      },
      {
        id: 'piscis-27-4',
        cycleId: 12,
        phaseIndex: 4,
        moon: '🌗',
        name: 'Cuarto Menguante',
        date: '2027-03-25',
        sign: 'Sagitario ♐',
        theme: 'El umbral final. Estás a punto de nacer de nuevo.',
        suggestions: [
          'Crea un ritual de finalización del año astrológico',
          'Descansa completamente antes del nuevo inicio',
          'Escribe una carta a tu yo del próximo año de Aries',
          'Confía: todo lo que necesitas para el nuevo ciclo ya está en ti',
        ],
      },
    ],
  },
];

export function getCurrentCycleAndPhase(): { cycle: Cycle; phase: Phase } | null {
  const today = new Date();
  today.setHours(0, 0, 0, 0);

  for (const cycle of CYCLES) {
    for (const phase of cycle.phases) {
      const phaseDate = new Date(phase.date);
      phaseDate.setHours(0, 0, 0, 0);

      // Find the next phase date
      const phaseIdx = cycle.phases.indexOf(phase);
      const nextPhase = cycle.phases[phaseIdx + 1];
      const nextCyclePhase = CYCLES[cycle.id + 1]?.phases[0];
      const endDate = nextPhase
        ? new Date(nextPhase.date)
        : nextCyclePhase
          ? new Date(nextCyclePhase.date)
          : new Date(cycle.endDate);
      endDate.setHours(0, 0, 0, 0);

      if (today >= phaseDate && today < endDate) {
        return { cycle, phase };
      }
    }
  }
  return null;
}

export function getAllPhases(): Phase[] {
  return CYCLES.flatMap((c) => c.phases);
}
